apiVersion: v1
kind: Service
metadata:
  name: {{ template "imgproxy.fullname" . }}
{{- if or .Values.annotations }}
  annotations:
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
{{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ .Release.Name | quote }}
spec:
  selector:
    app: {{ template "imgproxy.fullname" . }}
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
  type: {{ default "ClusterIP" .Values.serviceType }}
